
      
build:
 version: "1.0"
 
accounts:
 message: "Welcome to EazyBank accounts related prod APIs"
 contact-details:
  name: "Reine Aishwarya-Product Owner"
  email: "aishwarya@eazybank.com"
 onCallSupport:
  -(666)587-4765
  -(666)597-9371